import ProTwoOne from '../assets/Pro(2)1.jpg';
import ProTwoTwo from '../assets/Pro(2)2.jpg';
import ProTwoThree from '../assets/Pro(2)3.jpg';
import ProTwoFour from '../assets/Pro(2)4.jpg';
import ProTwoFive from '../assets/Pro(2)5.jpg';
import ProTwoSix from '../assets/Pro(2)6.jpg';
import ProTwoSeven from '../assets/Pro(2)7.jpg';
import ProTwoEight from '../assets/Pro(2)8.jpg';
import Pro1 from '../assets/Pro1.jpg';
import Pro2 from '../assets/Pro2.jpg';
import Pro3 from '../assets/Pro3.jpg';
import Pro4 from '../assets/Pro4.jpg';
import Pro5 from '../assets/Pro5.jpg';
import Pro6 from '../assets/Pro6.jpg';
import Pro7 from '../assets/Pro7.jpg';
import Pro8 from '../assets/Pro8.jpg';

const Product = [
    {
        _id:"1",
        code:"SKU: BJJ-HWD-BLK",
        img:Pro1,
        img1:ProTwoOne,
        price: 130,
        del_price: "$170",
        name: "HWD Jiu Jitsu GI",
        nameLink:"product/1",
        description: "Black.2 colors",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:[ "A-0","A-1","A-1H","A-2","A-1L","A-2H" ],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        key:1,
        Category:"Suits-Navy",
        // Category:"Suits-Black",
        del:"dl-img",
        Color:["White", "Black", "Blue"]
    },
    {
        _id:"2",
        code:"SKU: BJJ-HWD-NVY",
        img:Pro2,
        img1:ProTwoTwo,
        price: 230,
        del_price: "$170",
        name: "HWD Jiu Jitsu GI",
        nameLink:"product/2",
        description: "Navy.2 colors",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1","A-1H","A-2","A-1L","A-3L","A-4"],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        key:2,
        // Category:"Suits-Black",
        Category:"Suits-Navy",
        del:"dl-img",
        Color:["White","Black"] 
    },
    {
        _id:"3",
        code:"SKU: BJJ-V6-NVY",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        img:Pro3,
        img1:ProTwoThree,
        price: 120,
        del_price: "$145",
        name: "V6 BJJ GI + Free White Belt",
        nameLink:"product/3",
        description: "Navy Blue.4 colors",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1","A-1H","A-2"],
        class: "cl-img",
        key:3,
        Category:"V6-Womens",
        // Category:"V6-Mens",
        del:"dl-img",
        Color:["White"], 
    },
    {
        _id:"4",
        code:"SKU: BJJ-V6-NVY-F",
        img:Pro4,
        img1:ProTwoFour,
        price: 220,
        del_price: "$145",
        nameLink:"product/4",
        name: "V6 Womens BJJ GI + Free White Belt",
        description: "Navy Blue.4 colors",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1","A-1H"],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        slug:"v6-women-bjj-gjj",
        key:4,
        // Category:"V6-Mens",
        Category:"V6-Womens",
        del:"dl-img",
        Color:["White", "Black", "Blue"]
    },
    {
        _id:"5",
        code:"SKU: BJJ-V6-NVY-Y",
        img:Pro5,
        img1:ProTwoFive,
        price: 100,
        del_price: "$122",
        nameLink:"product/5",
        name: "V6 kids BJJ GI + Free White Belt",
        description: "Navy Blue.4 colors",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1"],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        key:5,
        Category:"Thai-Shorts",
        // Category:"V6-Kids",
        del:"dl-img",
        Color:["Black"] 
    },
    {
        _id:"6",
        code:"SKU: USA-JER-2-REV",
        img:Pro6,
        img1:ProTwoSix,
        price: 67,
        del_price: "$75",
        nameLink:"product/6",
        name: "2024 USA Muay Thai Jersey",
        description: "Reversible",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1","A-1H","A-2","A-1L","A-2H","A-2L","A-3","A-3H","A-3L","A-4"],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        key:6,
        // Category:"V6-Kids",
        Category:"Thai-Shorts",
        del:"dl-img",
        Color:["White"]
    },
    {
        _id:"7",
        code:"SKU: USA-MTS-2",
        img:Pro7,
        img1:ProTwoSeven,
        price: 37,
        del_price: "$75",
        nameLink:"product/7",
        name: "2024 USA Muay Thai Shorts",
        description: "Black",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1","A-1H","A-2","A-1L","A-2H","A-2L","A-3","A-3H","A-3L","A-4"],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        key:7,
        Category:"Singlet-Round",
        // Category:"Thai-Shorts",
        del:"dl-img",
        Color:["White","Black","Blue"]
    },
    {
        _id:"8",
        code:"SKU: SGT-C-BLK",
        img:Pro8,
        img1:ProTwoEight,
        price: 35,
        del_price: "$62",
        name: "C Singlet",
        nameLink:"product/8",
        description: "Black 2 colors",
        Quantity: 1,
        Total: 0,
        size: "Size: S/M",
        Size:["A-0","A-1","A-1H","A-2","A-1L","A-2H","A-2L","A-3"],
        class: "cl-img",
        link1: "Cancel",
        classA: "anchor",
        nameA: "Combat Corner",
        key:8,
        Category:"Singlet-Round",
        // Category:"Thai-Shorts",
        del:"dl-img",
        Color:["Blue"]
    }
]

export default Product;